//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.attachments = new HashSet<attachment>();
            this.collections = new HashSet<collection>();
            this.taggings = new HashSet<tagging>();
        }
    
        public int id { get; set; }
        public int article_type_id { get; set; }
        public int section_id { get; set; }
        public string title { get; set; }
        public string cached_number { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> declare_at { get; set; }
        public string registration_code { get; set; }
        public string contents { get; set; }
        public string number { get; set; }
        public int proceedings_id { get; set; }
        public Nullable<int> articles_id { get; set; }
    
        public virtual article_types article_types { get; set; }
        public virtual article articles1 { get; set; }
        public virtual article article1 { get; set; }
        public virtual proceedings proceedings { get; set; }
        public virtual section section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachment> attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collection> collections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tagging> taggings { get; set; }
    }
}
