//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public int id { get; set; }
        public int articles_id { get; set; }
        public int publishers_id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> article_type_id { get; set; }
    
        public virtual article article { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
