//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ovuEntities : DbContext
    {
        public ovuEntities()
            : base("name=ovuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article_types> article_types { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<attachment_types> attachment_types { get; set; }
        public virtual DbSet<attachment> attachments { get; set; }
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<proceedings> proceedings { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<tagging> taggings { get; set; }
        public virtual DbSet<tag> tags { get; set; }
    }
}
